# **Battle of Neighbourhoods for Establishment of Food Truck in Bangalore**

Importing all necessary libraries

In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

# for webscraping import Beautiful Soup 
from bs4 import BeautifulSoup

import xml

!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library



Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs: 
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geographiclib-1.49         |             py_0          32 KB  conda-forge
    openssl-1.1.1c             |       h516909a_0         2.1 MB  conda-forge
    ca-certificates-2019.6.16  |       hecc5488_0         145 KB  conda-forge
    geopy-1.20.0               |             py_0          57 KB  conda-forge
    certifi-2019.6.16          |           py36_1         149 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

    geographiclib:   1.49-py_0         conda-forge
    geopy:           1.20.0-py_0       conda-forge

The following packages will be UPDATED:

    ca-

Obtaining the co-ordinatates of out location using geolocator and mapping out the cities in Bangalore.

In [2]:
address ='Bengaluru'
geolocator =Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude= location.latitude
longitude= location.longitude
print(latitude,longitude)
map_blr = folium.Map(location=[latitude, longitude], zoom_start=10)
map_blr

12.9791198 77.5912997


Therefore the co-rdinates of Bangalore are 12.9791198 77.5912997.

In [3]:
table=pd.read_html('https://en.wikipedia.org/wiki/List_of_wards_in_Bangalore',header=0)
blr_df=table[0]
blr_df.head(200)

Ward number                        Ward name  \
0              1                       Kempegowda   
1              2                     Chowdeshwari   
2              3                            Attur   
3              4              Yelahanka Satellite   
4              5                           Jakkur   
5              6                      Thanisandra   
6              7                  Byatarayanapura   
7              8                      Kodigehalli   
8              9                   Vidyaranyapura   
9             10                 Doddabommasandra   
10            11                    Kuvempu Nagar   
11            12                      Shettyhalli   
12            13                      Mallasandra   
13            14                      Bagalagunte   
14            15                    T-Dasarahalli   
15            16                        Jalahalli   
16            17                         J.P.Park   
17            18              Radhakrishna Temple   
18            19                     Sanjay Nagar   
19            20                      Ganga Nagar   
20            21                           Hebbal   
21            22            Vishwanathnagenahalli   
22            23                         Nagavara   
23            24                       HBR Layout   
24            25                         Horamavu   
25            26                 Ramamurthy Nagar   
26            27                        Banaswadi   
27            28                     Kammanahalli   
28            29                 Kacharakanahalli   
29            30                 Kadugondanahalli   
30            31                     Kushal Nagar   
31            32                  Kavalbyrasandra   
32            33                  Manorayanapalya   
33            34                     Gangenahalli   
34            35                    Aramane Nagar   
35            36                        Mathikere   
36            37                     Yeshwanthpur   
37            38                            H.M.T   
38            39                     Chokkasandra   
39            40                 Dodda Bidarkallu   
40            41           Peenya Industrial Area   
41            42                Lakshmidevi Nagar   
42            43                   Nandini Layout   
43            44                  Marappana Palya   
44            45                     Malleshwaram   
45            46          Jayachamarajendra Nagar   
46            47               Devarajeevanahalli   
47            48                 Muneshwara Nagar   
48            49                   Lingarajapuram   
49            50                   Benniganahalli   
50            51                      Vignanapura   
51            52                        K.R.Puram   
52            53                     Basavanapura   
53            54                            Hoodi   
54            55                       Devasandra   
55            56                   A.Narayanapura   
56            57                  C.V.Raman Nagar   
57            58                 Hosathippasandra   
58            59                Maruthiseva Nagar   
59            60                      Sagayapuram   
60            61                       S.K.Garden   
61            62                  Ramaswamy Palya   
62            63                        Jayamahal   
63            64                        Rajamahal   
64            65                  Kadumalleshwara   
65            66                 Subramanya Nagar   
66            67                         Nagapura   
67            68                 Mahalakshmipuram   
68            69                          Laggere   
69            70                 Rajagopala Nagar   
70            71                     Hegganahalli   
71            72                        Herohalli   
72            73                     Kottigepalya   
73            74           Shakthiganapathi Nagar   
74            75              

Getting Ready to Use FourSquare API

In [4]:
CLIENT_ID = 'EKWL1N0YNTXRLUVSFLYD5EDKHSNEJ4BQ2E3RKQUDBOPFVIUZ' # Foursquare ID
CLIENT_SECRET = 'ML13RPWBSIXUSX4TSXM4OWPCOSYEBJWAUYX1DHI3WH3XJAUQ' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
categoryId = '4bf58dd8d48988d1cb941735'
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: EKWL1N0YNTXRLUVSFLYD5EDKHSNEJ4BQ2E3RKQUDBOPFVIUZ
CLIENT_SECRET:ML13RPWBSIXUSX4TSXM4OWPCOSYEBJWAUYX1DHI3WH3XJAUQ


Now we will use FourSquare API and creating a function to get all the nearyby food trucks.

In [5]:

def getNearbyfoodtrucks(latitude, longitude, radius=5000):
    
    url = 'https://api.foursquare.com/v2/venues/explore?&categoryId={}&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    categoryId,
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude, 
    longitude, 
    radius, 
    LIMIT)
    
    venues_list=[]
    
    results = requests.get(url).json()["response"]['groups'][0]['items']

    for item in results:
        venue = item['venue']
        venues_list.append([(
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    
    nearby_venues.columns = ['Name', 
                'Latitude', 
                'Longitude', 
                'Venue Type']
    
    return(nearby_venues)

Calling the created function to get the list.

In [6]:
events_venues = getNearbyfoodtrucks(latitude=12.97194, longitude=77.59369)
events_venues.drop_duplicates(inplace = True)
events_venues.head(50)

Name   Latitude  Longitude  \
0                                  Ganesh Chat Centre  12.951538  77.578797   
1                                        Nagarathpeth  12.967582  77.579362   
2                                  Chancery Pan Walla  12.975525  77.599682   
3                                   Unisys Chai Tapri  12.966671  77.598850   
4                                     Koshy's Panwala  12.974791  77.601405   
5                                       Tibbs Frankie  12.976051  77.603750   
6                                  Lazeez Katti Rolls  12.972524  77.607079   
7                                       Tibbs Frankie  12.980953  77.606866   
8                                        Narayan Idly  12.964024  77.578008   
9   Basavanagudi Egg Special(National College Circle)  12.948426  77.574297   
10                  Tibbs Frankie (Commercial Street)  13.001938  77.599061   
11                        Madhavan Park Bhajji Center  12.936121  77.585183   
12                                      Tibbs Frankie  13.000151  77.617899   
13                               davangere benne dosa  13.001532  77.564122   
14                                           DVG Road  12.942025  77.571096   
15                                     Egg Fried Rice  13.005958  77.564917   
16                        Davanagere Benne Dose Hotel  12.928792  77.586847   

    Venue Type  
0   Food Truck  
1   Food Truck  
2   Food Truck  
3   Food Truck  
4   Food Truck  
5   Food Truck  
6   Food Truck  
7   Food Truck  
8   Food Truck  
9   Food Truck  
10  Food Truck  
11  Food Truck  
12  Food Truck  
13  Food Truck  
14        Road  
15  Food Truck  
16  Food Truck

Map the venues.

In [7]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=13)

for lat, lon in zip(events_venues['Latitude'], events_venues['Longitude']):
    folium.CircleMarker(
        [lat, lon],
        radius=3,
        fill=True,
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

Based on the venues shown on the map, we would want to locate our food truck in the busiest locations. Therefore we will use **K-Means to find the most completive spot out there, then grab the lat,long and convert to a list** .

In [8]:

X = events_venues[['Latitude', 'Longitude']] # define X

In [9]:
k_means = KMeans(init="k-means++", n_clusters=1, n_init=12) # Initiate KMeans
k_means.fit(X) #Fit it

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=1, n_init=12, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [10]:
k_means_cluster_centers = k_means.cluster_centers_
opt = k_means_cluster_centers # Use this to find the custer center

In [11]:
opt = opt[0].tolist() # Convert to a list

Adding the best spot to the map.

In [12]:
map_final = folium.Map(location=[latitude, longitude], zoom_start=13)

for lat, lon in zip(events_venues['Latitude'], events_venues['Longitude']):
    folium.CircleMarker(
        [lat, lon],
        radius=3,
        fill=True,
        fill_opacity=0.7).add_to(map_final)

folium.CircleMarker(opt, radius = 4, fill = True, color = 'red').add_to(map_final)
map_final

In [58]:
print('The location of the food truck store should be', opt)

The location of the food truck store should be [12.970270757274333, 77.58924823681946]
